name: Java CI with Bach.java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Build with Bach.java'
      run: jshell https://sormuras.de/bach@11.3-M1/build
