name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: 'Build with Bach'
      run: |
        PATH=$PATH:.bach/bin
        bach build --project-name greetings --project-version 1
